from .settings import ConversionSettings

PRESETS: dict[str, ConversionSettings] = {
    "Foto": ConversionSettings(
        colormode='color',
        hierarchical='stacked',
        mode='spline',
        filter_speckle=4,
        color_precision=6,
        layer_difference=16,
        corner_threshold=60,
        length_threshold=4.0,
        contrast=1.05,
        saturation=1.1,
        sharpness=1.05,
    ),
    "Logo": ConversionSettings(
        colormode='color',
        hierarchical='cutout',
        mode='spline',
        filter_speckle=8,
        color_precision=4,
        layer_difference=4,
        corner_threshold=70,
        length_threshold=3.0,
        contrast=1.1,
        saturation=1.0,
        sharpness=1.0,
    ),
    "Ilustración": ConversionSettings(
        colormode='color',
        hierarchical='stacked',
        mode='spline',
        filter_speckle=2,
        color_precision=7,
        layer_difference=8,
        corner_threshold=50,
        length_threshold=3.5,
        contrast=1.0,
        saturation=1.05,
        sharpness=1.0,
    ),
    "Alta calidad": ConversionSettings(
        colormode='color',
        hierarchical='stacked',
        mode='spline',
        filter_speckle=2,
        color_precision=8,
        layer_difference=4,
        corner_threshold=45,
        length_threshold=2.0,
        max_iterations=20,
        contrast=1.0,
        saturation=1.0,
        sharpness=1.0,
    ),
    "Borrador": ConversionSettings(
        colormode='color',
        hierarchical='stacked',
        mode='polygon',
        filter_speckle=16,
        color_precision=4,
        layer_difference=32,
        corner_threshold=80,
        length_threshold=6.0,
        max_iterations=5,
        contrast=1.0,
        saturation=1.0,
        sharpness=1.0,
    ),
    "B&N": ConversionSettings(
        colormode='binary',
        hierarchical='stacked',
        mode='spline',
        filter_speckle=4,
        color_precision=1,
        layer_difference=128,
        corner_threshold=60,
        length_threshold=4.0,
        contrast=1.2,
        saturation=0.0,
        sharpness=1.2,
    ),
}
